services:
  api:
    build: .
    container_name: sunsetting-api
    env_file:
      - .env
      - .env.docker
    networks:
      - sunsetting-net
  caddy:
    build: ./caddy
    container_name: sunsetting-caddy
    networks:
      - sunsetting-net
    env_file:
      - .env
      - .env.docker
    volumes:
      # 配置文件
#      - ./caddy/Caddyfile.normal:/data/Caddyfile
      - ./caddy/Caddyfile.proxy:/data/Caddyfile
      # 持久化
      - /root/caddy-data:/data/caddy
      # 前端
      - /root/html:/root/html
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "9180:9180/tcp"
      - "9180:9180/udp"
  redis:
    image: redis:7.2-alpine
    container_name: sunsetting-redis
    networks:
      - sunsetting-net

networks:
  sunsetting-net:
    name: sunsetting-net
